app/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('auth/', include('user.urls')),
    path('tournament/', include('tournament.urls'))
)

tournament/api/urls.py
from django.urls import path

urlpatterns = [

]

tournament/urls.py
from django.urls import path

urlpatterns = [

]

user/urls.py
from django.urls import path
from .views import auth

urlpatterns = [
    path('login/', auth.login_view, name='login'),
    path('logout/', auth.logout_view, name='logout'),
    path('registration/', auth.registration_view, name='registration'),

]

tournament/models.py
from django.db import models
from django.contrib.auth.models import User

from user.models import Participant


class Tournament(models.Model):
    """
        Турнир
    """
    RANGS = (
        ('Клубный', 'Клубный'),
        ('Городской', 'Городской'),
        ('Областной', 'Областной'),
        ('Региональный', 'Региональный'),
        ('Республиканский', 'Республиканский'),
        ('Чемпионат РК', 'Чемпионат РК'),
        ('Международный турнир', 'Международный турнир'),
    )

    CREDIT_TYPE = (
        ('личный', 'личный'),
        ('командный', 'командный')
    )

    STATUS = (
        ('Регистрация открыта', 'Регистрация открыта'),
        ('Регистрация завершенa', 'Регистрация завершенa'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    title = models.CharField(max_length=300, verbose_name='Title')
    slug = models.SlugField(max_length=300, unique=True, default='')
    logo = models.ImageField(upload_to='tournament_logo', blank=True)
    logos = models.ManyToManyField('Logos', default=[], blank=True, related_name='logos')
    about = models.TextField(max_length=3000, blank=True)

    rang = models.CharField(max_length=40, choices=RANGS, blank=True)

    place = models.CharField(max_length=100, blank=True)

    startData = models.DateField(max_length=100, blank=True)
    finishData = models.DateField(max_length=100, blank=True)
    startTime = models.TimeField(max_length=10, blank=True)

    credit = models.CharField(max_length=100, blank=True, choices=CREDIT_TYPE)

    tatamis_count = models.CharField(default=0, blank=True, max_length=2)

    sponsors = models.ManyToManyField('Sponsors', blank=True, default=[], related_name='sponsors')

    chiefJustice = models.CharField(Participant, on_delete=models.CASCADE, blank=True)
    chiefSecretary = models.CharField(Participant, on_delete=models.CASCADE, blank=True)
    status = models.CharField(max_length=40, choices=STATUS, default='Регистрация_открыта')

    public = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.title


class Weight(models.Model):
    """
        Вес
    """
    name = models.CharField(max_length=10)
    sorting = models.JSONField(blank=True, null=True)

    participants = models.ManyToManyField(Participant, default=[], blank=True)

    def __str__(self):
        return self.name

class WeightCategory(models.Model):
    """
        Весовая категория
    """
    GENDER = (
        ('Мужской', 'Мужской'),
        ('Женский', 'Женский')
    )

    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, blank=True)
    weight = models.ManyToManyField(Weight, default=[])

    year = models.CharField(max_length=20, null=True)
    gender = models.CharField(max_length=20, choices=GENDER)

    def delete(self):
        weights = self.weight.all()

        for w in weights:
            w.delete()

        super(WeightCategory, self).delete()

    def __str__(self):
        return self.year


class Logos(models.Model):
    """
        Логотипы турниров
    """
    image = models.ImageField(upload_to='tournaments_logos')

    def __str__(self):
        return self.image.name


class Sponsors(models.Model):
    """
        Спонсоры турниров
    """
    image = models.ImageField(upload_to='sponsors', blank=True)

    def __str__(self):
        return self.image.name

user/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    """
        Профиль пользователя
    """
    TASKS = (
        ('Админ', 'Админ'),
        ('Секретарь', 'Секретарь'),
        ('Свободный', 'Свободный')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    fullName = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=12, blank=True)

    organization = models.CharField(max_length=300, blank=True)

    city = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)

    userType = models.CharField(max_length=20, choices=TASKS, default='Свободный')

    def avatar_directory_path(instance, filename) -> str:
        username = instance.user.username if instance.user else 'unknown_user'
        extension = filename.split('.')[-1]
        new_filename = f'{username}_document_{uuid.uuid4().hex[:10]}.{extension}'
        return f'uploads/users/{username}/avatars/{new_filename}'

    image = models.ImageField(upload_to=avatar_directory_path, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class Participant(models.Model):
    """
        Участник
    """
    EVENT_FUNCTIONS = (
        ('Спортсмен', 'Спортсмен'),
        ('Тренер', 'Тренер'),
        ('Судья', 'Судья'),
    )

    JUDGE_TYPE = (
        ('Судейско-вспомогательный персонал', 'Судейско-вспомогательный персонал'),
        ('Арбитр', 'Арбитр'),
        ('Информатор', 'Информатор'),
        ('Секретариат', 'Секретариат'),
        ('Судейская комиссия', 'Судейская комиссия'),
        ('Руководитель татами (комиссар)', 'Руководитель татами (комиссар)'),
        ('Главный секретарь', 'Главный секретарь'),
        ('Главный судья', 'Главный судья'),
    )

    GENDER = (
        ('Мужской', 'Мужской'),
        ('Женский', 'Женский')
    )

    DISCHARGES = (
        ('Белый пояс (мукю)', 'Белый пояс (мукю)'),
        ('Желтый пояс (10 кю)', 'Желтый пояс (10 кю)'),
        ('Оранжевый пояс (9 кю)', 'Оранжевый пояс (9 кю)'),
        ('Зеленый пояс (8 кю)', 'Зеленый пояс (8 кю)'),
        ('Синий пояс (7 кю)', 'Синий пояс (7 кю)'),
        ('Коричневый пояс (6 кю - 1 кю)', 'Коричневый пояс (6 кю - 1 кю)'),
        ('Черный пояс (1 дан - 10 дан)', 'Черный пояс (1 дан - 10 дан)'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    thirdName = models.CharField(max_length=100, blank=True)

    def participant_directory_path(instance, filename) -> str:
        username = instance.user.username if instance.user else 'unknown_user'
        fio = f'{instance.firstName} {instance.lastName} {instance.thirdName}'

        extension = filename.split('.')[-1]
        new_filename = f'{username}_document_{uuid.uuid4().hex[:10]}.{extension}'

        return f'uploads/users/{username}/participants/{fio}/images/{new_filename}'

    event_function = models.CharField(max_length=10, choices=EVENT_FUNCTIONS)

    ava = models.ImageField(upload_to=participant_directory_path, blank=True)

    year = models.DateField(null=True, blank=True)
    discharge = models.CharField(max_length=40, choices=DISCHARGES, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, blank=True)
    coach = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, related_name='sports_coach')
    judge_type = models.CharField(max_length=40, choices=JUDGE_TYPE, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {} {}'.format(self.firstName, self.lastName, self.thirdName)

user/forms/user_forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


"""
   Форма для создания пользователя
"""
class CreateUserForm(UserCreationForm):
   class Meta:
      model = User
      fields = ['username', 'email', 'password1','password2']

"""
   Форма для обновления главной информации пользователя
"""
class UpdateUserForm(ModelForm):
   class Meta:
      model = User
      fields = ['username', 'email']

tournament/views.py
from django.shortcuts import render

# Create your views here.

back/base/templates/base/tournaments/show_tournament.html
{% include 'main.html' %}
{% load static i18n %}

{% block title %}
<link rel="stylesheet" href="{% static 'css/tournaments/tournament_show.css' %}">
<title>{% trans 'Tournament' %}</title>
{% endblock title %}
   
{% block content %}
<div class="tournament">
   <div class="tournament__menu">
      
      <a class="tournament__weight__category__link" href="{% url 'base:tournamet_show' tournament.slug %}">
         {% trans 'Categories' %}
      </a>
      
      {% for weight_category in tournament.weightcategory_set.all  %}
         <a class="tournament__weight__category">
            <i class="fa-solid fa-list"></i>
            <h4>{{weight_category.gender}} {{weight_category.year}}</h4>
         </a>
      {% endfor %}
   </div>
   <div class="tournament__left">
      <h3>{{ tournament.title }}</h3>
      <p>
         <i class="fa-solid fa-calendar-days"></i> 
         {% trans 'Date' %}: {{tournament.startData}} - {{tournament.finishData}}
         <i class="fa-regular fa-clock"></i>
         {% trans 'Time' %}: {{tournament.startTime}}
         {% trans 'status' %}
      </p>
      <p>
         <i class="fa-solid fa-users"></i> {% trans 'Participants' %}: {{person_count }}
      </p>
      <p>   
         <i class="fa-solid fa-location-dot"></i> {% trans 'Location' %}: {{tournament.place}}
         <i class="fa-solid fa-ranking-star"></i> {% trans 'Rang' %}: {{tournament.rang}}
      </p>
      <div class="slider">
         <button id="slider__left" >
            <i class="fa-solid fa-chevron-left"></i>
         </button>

         <img src="" alt="" id="slider__gallery">
         
         <button id="slider__right">
            <i class="fa-solid fa-chevron-right"></i>
         </button>
      </div>
      <div class="tournament__images" id="images__collection">
         {% for logo in tournament.logos.all %}
            <img src="/static/media/{{logo.image}}" alt="{{ image.name }}" class="slider__image">
         {% endfor %}
      </div>
      <p>
         <i class="fa-solid fa-user-tie"></i> {% trans 'Chief Justice' %}: {{ tournament.chiefJustice}}
      </p>
      <p>
         <i class="fa-solid fa-user-tie"></i> {% trans 'Chief Secretary' %}: {{ tournament.chiefSecretary }}
      </p>
      <p>   
         <i class="fa-solid fa-highlighter"></i>{% trans 'About' %}: {{tournament.about}}
      </p>
      <p class="tournament__sponsors">
         <span>
            <i class="fa-solid fa-users"></i>
            {% trans 'Sponsors' %}: </span>
         {% for sponsor in tournament.sponsors.all %}
         <img src="/static/media/{{sponsor.image}}" alt="{{ sponsor.name }}">
         {% endfor %}
      </p>
   </div>
   <div class="tournament__right">
      <div class="tournament__right__participants">{% trans 'Registration' %}:  {{tournament.status}}</div>
      <div class="tournament__right__participants">{% trans 'Number of participants' %}:  0</div>
   </div>
</div>

<script src="{% static '/js/gallery.js' %}"></script>
{% endblock content %}  

templates/header.html
{% load static i18n  %}

<header>
   <a href="/" class="link-logo">
      <b>JUDO</b>

      <span>
         <span>KZ</span>
      </span>
   </a>

   <div class="mobile__menu">
      <i class="fa-solid fa-bars"></i>
   </div>

   {% comment %}<div class="header__center">
      <a href="" class="link">
         {% trans 'Турниры' %}
         <i class="fa-solid fa-calendar-days"></i>
      </a>
      <a href="" class="link">
         {% trans 'Медали' %}
         <i class="fa-solid fa-medal"></i>
      </a>
      <a href="" class="link">
         {% trans 'Сортировка' %}
         <i class="fa-solid fa-arrow-up-wide-short"></i>
      </a>
      <a href="{% url "instructions" %}" class="link">
         {% trans 'Инструкции' %}
         <i class="fa-solid fa-circle-info"></i>
      </a>
   </div> {% endcomment %}

   <div class="header__right">
      {% if request.user.is_authenticated  %}
      {% if request.user.profile.userType == 'Админ' or request.user.profile.userType == 'Секретарь' or request.user.is_superuser %}
         <a href="" class="link"
         style="font-size: 30px; font-weight: bold;">
            +
            <!-- {% trans 'Add New Tournament' %} -->
         </a>
      {% endif %}
   <a href="{% url 'show_profile' request.user.username %}" class="link">
      {{ request.user.username }}
   </a>
   <a href="{% url 'logout' %}" class="link">
      {% trans 'Выход' %}
   </a>
{% else %}
   <a href="{% url 'registration' %}" class="link">{% trans 'Регистрация' %}</a>
   <a href="{% url 'login' %}" class="link">{% trans 'Вход' %}</a>
{% endif %}
   <form action="{% url 'set_language' %}" method="post" id="LanguageForm">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language" id="changeLanguage" class='change__language' >
         {% get_current_language as LANGUAGE_CODE %}
         {% get_available_languages as LANGUAGES %}
         {% get_language_info_list for LANGUAGES as languages %}
         {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                     selected{% endif %}>
                  {% comment %} {{ language.name_local }}  {% endcomment %}
                  {{ language.code }}
            </option>
         {% endfor %}
      </select>
      <!-- <button type="submit" class="btn">{% trans 'Translate' %}</button> -->
   </form>
   </div>

</header>

<script>
   document.getElementById("changeLanguage").addEventListener("change", function() {
      document.getElementById("LanguageForm").submit();
   });
</script>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <link rel="stylesheet" href="{% static 'css/styles.css' %}">
   <link rel="stylesheet" href="{% static 'css/footer.css' %}">

   {% block title %}{% endblock title %}
</head>
<body>
    <div class="global__messages">
        {% for message in messages %}
            <div class='global__message'>
                {{message}}
            </div>
        {% endfor %}
    </div>
        {% include 'header.html' %}
        {% block content %}{% endblock content %}



   <script src="{% static 'js/message.js' %}"></script>
   <script src="{% static 'js/header.js' %}"></script>
   <script src="https://kit.fontawesome.com/0b77448ae5.js" crossorigin="anonymous"></script>

    </body>
</html>

user/templates/user/auth.html
{% include 'main.html' %}
{% load static i18n %}

{% block title %}
   <link rel="stylesheet" href="{% static 'user/css/auth.css' %}">
   {% if page_type == 'login' %}
      <title>
         {% trans 'Вход' %}
      </title>
   {% else %}
      <title>
         {% trans 'Регистрация' %}
      </title>
   {% endif %}
{% endblock title %}


{% block content %}
   <div class="pre__form">
      <form method="POST">
         {% csrf_token %}

         {% if page_type == 'login' %}
            <h1>{% trans 'Вход' %}</h1>
            <p>{% trans 'Пожалуйста, введите логин и пароль для продолжения использования сайта.' %}</p>

            <div class = "form__component">
               <label>{% trans 'Электронная почта' %}:</label>
               <input type="email" name="email" id="email" required />
            </div>

            <div class = "form__component">
               <label>{% trans 'Пароль' %}:</label>
               <input type="password" name="password" id="password" required />
            </div>
         {% else %}
            <h1>{% trans 'Регистрация' %}</h1>
            <p>{% trans 'Пожалуйста, зарегестрируйтесь для продолжения использования сайта.' %}</p>

            {% for field in form  %}
               {% if field.errors %}
               <ul class="errorlist">
                  {% for error in field.errors %}
                  <li>{{ error }}</li>
                  {% endfor %}
               </ul>
               {% endif %}
            {% endfor %}

            <div class = "form__component">
               <label>{% trans 'Имя пользователя' %}:</label>
               {{ form.username }}
            </div>

            <div class = "form__component">
               <label>{% trans 'Электронная почта' %}:</label>
               {{ form.email }}
            </div>

            <div class = "form__component">
               <label>{% trans 'Пароль' %}:</label>
               {{ form.password1 }}
            </div>

            <div class = "form__component">
               <label>{% trans 'Подтверждение пароля' %}:</label>
               {{ form.password2 }}
            </div>

         {% endif %}

         <button type="submit" class="btn">{% trans 'Продолжить' %}</button>

         {% if page_type == 'login' %}
            <p>{% trans 'Впервые?' %} <a href="{% url 'registration' %}">{% trans 'Создать аккаунт' %}</a></p>
         {% else %}
            <p>{% trans 'Уже имеете аккаунт?' %} <a href="{% url 'login' %}">{% trans 'Войти в созданный' %}</a></p>
         {% endif %}
      </form>
   </div>
{% endblock content %}